blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/csuermann/node-red-contrib-virtual-smart-home?tab=readme-ov-file#faq
    about: The answer to your question might already be there
  - name: PRO plan
    url: https://billing.stripe.com/p/login/6oE00vdQ62Tp3LidQQ
    about: Manage your PRO plan subscription
